Repository fga-eps-mds/2022-2-CAPJu-Interface, pull requests merged in 2022-12, with the labels that each got.

#22 Melhoria nas cores
  src/components/FlowViewer/FlowViewer.jsx
  src/components/SideBar/ModalHeader.jsx
  src/pages/AccessProfile/AccessProfile.jsx
  src/pages/Flows/Flows.jsx
  src/pages/Login/Login.jsx
  src/pages/Processes/Processes.jsx
  src/pages/Processes/styles.js
  src/pages/Recovery/Login.jsx
  src/pages/SolicitacoesCadastro/SolicitacoesCadastro.jsx
  src/pages/SolicitacoesCadastro/styles.js
  src/pages/Stages/Stages.jsx
  src/pages/StatisticsProcesses/Processes.jsx
  src/pages/Unidades/Unidades.jsx
Labels: Melhorias

#48 46-Correção da modal de novas anotações.
  src/components/ModalBody/styles.js
  src/components/ModalHeader/styles.js
  src/pages/ShowProcess/ShowProcess.jsx
Labels: MDS

#52 Remoção de componentes ligados a estatísticas
  src/App.js
  src/pages/Statistics/Statistics.jsx
  src/pages/Statistics/styles.js
  src/pages/StatisticsProcesses/Processes.jsx
  src/pages/StatisticsProcesses/styles.js
Labels: HOTFIX, EASY

#51 Cobertura de testes para pagina Perfil de Acesso
  src/__tests__/test_roles.js
  src/pages/AccessProfile/AccessProfile.jsx
Labels: EPS, MEDIUM

#53 Correção de erro em testes da interface
  src/__tests__/test_app.js
Labels: EPS, HOTFIX, EASY

#60 Valida nome/sobrenome em cadastro
  src/__tests__/test_register.js
  src/pages/Login/Login.jsx
  src/validators/registryValidator.js
Labels: enhancement, MDS

#59 Troca de email para CPF no login
  src/__tests__/test_login.js
  src/pages/Login/Login.jsx
Labels: enhancement, MDS

#58 Editar e deletar anotações
  src/components/FlowViewer/EdgeButton.jsx
  src/components/FlowViewer/FlowViewer.jsx
  src/components/FlowViewer/styles.js
  src/pages/AccessProfile/AccessProfile.jsx
  src/pages/Flows/Flows.jsx
  src/pages/ShowProcess/ShowProcess.jsx
Labels: FEATURE, MEDIUM

#61 Removendo abertura e fechamento de componentes não necessários
  src/components/TextInput/TextInput.jsx
  src/pages/Login/Login.jsx
  src/pages/Processes/Processes.jsx
  src/pages/Recovery/Login.jsx
  src/pages/Stages/Stages.jsx
  src/pages/Unidades/Unidades.jsx
  src/services/api.js
  src/services/user.js
Labels: Refatoração
