Repository fga-eps-mds/2022-2-CAPJu-Interface, pull requests merged in 2023-01, with the labels that each got.

#63 Refactor/139 retirada de ternarios
  src/__tests__/test_process.js
  src/components/Button/styles.js
  src/components/FlowViewer/FlowViewer.jsx
  src/components/SideBar/ModalHeader.jsx
  src/pages/Processes/Processes.jsx
  src/setupTests.js
Labels: Refatoração, MDS

#68 Novo layout de adicionar fluxo
  src/App.js
  src/__tests__/test_acceptRequest.js
  src/__tests__/test_flows.js
  src/components/AddSequenceInFlow/AddSequenceInFlow.jsx
  src/components/AddStageInFlow/AddStageInFlow.jsx
  src/components/AddStageInFlow/styles.js
  src/components/Button/styles.js
  src/components/Flow/AddSequenceInFlow.jsx
  src/components/Flow/EdgeButton.jsx
  src/components/Flow/FlowViewer.jsx
  src/components/Flow/SelectionList.jsx
  src/components/Flow/styles.js
  src/components/FlowViewer/styles.js
  src/components/SelectionList/styles.js
  src/components/TextInput/TextInput.jsx
  src/globalStyles.js
  src/pages/Flows/Flows.jsx
  src/pages/Flows/styles.js
  src/pages/Processes/Processes.jsx
  src/pages/ShowProcess/ShowProcess.jsx
  src/testConstants.js
Labels: enhancement, FEATURE

#67 Controle da visualização das opções do sistema através do perfil
  src/App.js
  src/__tests__/test_acceptRequest.js
  src/__tests__/test_flows.js
  src/__tests__/test_process.js
  src/__tests__/test_sideBar.js
  src/__tests__/test_stage.js
  src/__tests__/test_units.js
  src/components/Button/Button.jsx
  src/components/SideBar/Sidebar.jsx
  src/components/Tables/Table.jsx
  src/globalStyles.js
  src/pages/AccessProfile/AccessProfile.jsx
  src/pages/EditAccountEmail/EditAccountEmail.jsx
  src/pages/Flows/Flows.jsx
  src/pages/Login/Login.jsx
  src/pages/Processes/Processes.jsx
  src/pages/Recovery/Login.jsx
  src/pages/ShowProcess/ShowProcess.jsx
  src/pages/SolicitacoesCadastro/SolicitacoesCadastro.jsx
  src/pages/Stages/Stages.jsx
  src/pages/Unidades/Unidades.jsx
  src/testConstants.js
  src/util/permissionChecker.js
  src/validators/cpfValidator.js
Labels: US

#70 Feature/97 cadastro processos com prioridade
  src/__tests__/test_process.js
  src/__tests__/test_searchProcesses.js
  src/pages/Processes/Processes.jsx
  src/pages/Processes/styles.js
  src/testConstants.js
Labels: MDS, FEATURE
